<a href="https://colab.research.google.com/github/EatTooMuchEveryDay/me/blob/main/COMP576.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import io, integrate, linalg, signal
from scipy.sparse.linalg import eigs

In [ ]:
a=np.array([[1,2,3]])
np.ndim(a)

2

In [ ]:
np.size(a)

3

In [ ]:
np.shape(a)

(1, 3)

In [ ]:
a.shape[0]

1

In [ ]:
np.array([[1. ,2. ,3.], [4. ,5. ,6.]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
np.block([[1,2],[2,3]])

array([[1, 2],
       [2, 3]])

In [ ]:
a[-1]

array([1, 2, 3])

In [ ]:
b=np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20],[21,22,23,24,25,26,27,28,29,30]])
b[1,2]

13

In [ ]:
b[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
b[:2]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
b[-1:]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
b[0:2,1:3]

array([[ 2,  3],
       [12, 13]])

In [ ]:
b[np.ix_([0, 1], [1, 2])]

array([[ 2,  3],
       [12, 13]])

In [ ]:
b[1:8:1,:]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
b[ ::2,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
b[::-1,:]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
b[np.r_[:len(b),0]]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
b.T

array([[ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23],
       [ 4, 14, 24],
       [ 5, 15, 25],
       [ 6, 16, 26],
       [ 7, 17, 27],
       [ 8, 18, 28],
       [ 9, 19, 29],
       [10, 20, 30]])

In [ ]:
b.conj().T

array([[ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23],
       [ 4, 14, 24],
       [ 5, 15, 25],
       [ 6, 16, 26],
       [ 7, 17, 27],
       [ 8, 18, 28],
       [ 9, 19, 29],
       [10, 20, 30]])

In [ ]:
a@b

array([[ 86,  92,  98, 104, 110, 116, 122, 128, 134, 140]])

In [ ]:
a.T*b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [22, 24, 26, 28, 30, 32, 34, 36, 38, 40],
       [63, 66, 69, 72, 75, 78, 81, 84, 87, 90]])

In [ ]:
c=np.array([[4,5,6]])
a/c

array([[0.25, 0.4 , 0.5 ]])

In [ ]:
a**3

array([[ 1,  8, 27]])

In [ ]:
(a>0.5)

array([[ True,  True,  True]])

In [ ]:
np.nonzero(a > 0.5)

(array([0, 0, 0]), array([0, 1, 2]))

In [ ]:
v=np.array([1,2,3])
a[:,np.nonzero(v > 0.5)[0]]

array([[1, 2, 3]])

In [ ]:
a[:, v.T > 0.5]

array([[1, 2, 3]])

In [ ]:
a[a < 0.5]=0

In [ ]:
a * (a > 0.5)

array([[1, 2, 3]])

In [ ]:
a[:] = 3

In [ ]:
d = a.copy()

In [ ]:
d = a[0, :].copy()

In [ ]:
d = a.flatten()

In [ ]:
np.r_[1.:11.]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.r_[:10.]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.arange(1.,11.)[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.diag(a)

array([1])

In [ ]:
np.diag(v, 0)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
from numpy.random import default_rng
rng = default_rng(42)
rng.random(3)

array([0.77395605, 0.43887844, 0.85859792])

In [ ]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [ ]:
np.mgrid[0:9.,0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [ ]:
np.ix_(np.r_[0:9.],np.r_[0:6.])

(array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]), array([[0., 1., 2., 3., 4., 5.]]))

In [ ]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]), array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [ ]:
np.ix_([1,2,4],[2,4,5])

(array([[1],
        [2],
        [4]]), array([[2, 4, 5]]))

In [ ]:
np.tile(a, (2, 3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [ ]:
np.concatenate((a,c),1)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.concatenate((a,c))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.max()

3

In [ ]:
a.max(0)

array([1, 2, 3])

In [ ]:
a.max(1)

array([3])

In [ ]:
np.maximum(a, c)

array([[4, 5, 6]])

In [ ]:
np.sqrt(v @ v)

3.7416573867739413

In [ ]:
np.logical_and(a,c)

array([[ True,  True,  True]])

In [ ]:
np.logical_or(a,c)

array([[ True,  True,  True]])

In [ ]:
a & c

array([[0, 0, 2]])

In [ ]:
a | c

array([[5, 7, 7]])

In [ ]:
d=np.array([[1,2],[3,4]])
linalg.inv(d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
linalg.pinv(d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.matrix_rank(d)

2

In [ ]:
linalg.lstsq(a.T, b)

(array([[ 6.14285714,  6.57142857,  7.        ,  7.42857143,  7.85714286,
          8.28571429,  8.71428571,  9.14285714,  9.57142857, 10.        ]]),
 array([3.47142857e+01, 2.74285714e+01, 2.10000000e+01, 1.54285714e+01,
        1.07142857e+01, 6.85714286e+00, 3.85714286e+00, 1.71428571e+00,
        4.28571429e-01, 6.31088724e-29]),
 1,
 array([3.74165739]))

In [ ]:
linalg.svd(a)

(array([[-1.]]),
 array([3.74165739]),
 array([[-0.26726124, -0.53452248, -0.80178373],
        [-0.53452248,  0.77454192, -0.33818712],
        [-0.80178373, -0.33818712,  0.49271932]]))

In [ ]:
linalg.cholesky(d)

LinAlgError: ignored

In [ ]:
linalg.eig(d)

(array([-0.37228132+0.j,  5.37228132+0.j]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
linalg.eig(d, d)

(array([1.+0.j, 1.+0.j]), array([[-1., -0.],
        [-0., -1.]]))

In [ ]:
eigs(d, k = 2)

(array([-0.37228132+0.j,  5.37228132+0.j]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
linalg.qr(a)

(array([[1.]]), array([[1., 2., 3.]]))

In [ ]:
linalg.lu(a)

(array([[1.]]), array([[1.]]), array([[1., 2., 3.]]))

In [ ]:
cg

NameError: ignored

In [ ]:
np.ftt(a)

AttributeError: ignored

In [ ]:
np.ifft(a)

AttributeError: ignored

In [ ]:
np.sort(a)

array([[1, 2, 3]])

In [ ]:
np.sort(d, axis = 1)

array([[1, 2],
       [3, 4]])

In [ ]:
I = np.argsort(a[:, 0]); e = a[I,:]
e

array([[1, 2, 3]])

In [ ]:
linalg.lstsq(a, c)

(array([[0.28571429, 0.35714286, 0.42857143],
        [0.57142857, 0.71428571, 0.85714286],
        [0.85714286, 1.07142857, 1.28571429]]),
 array([], dtype=float64),
 1,
 array([3.74165739]))

In [ ]:
signal.resample(b, np.ceil(2))

TypeError: ignored

In [ ]:
np.unique(a)

array([1, 2, 3])

In [ ]:
a.squeeze()

array([1, 2, 3])